[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "5000"
SCRAPER_API_KEY = "your-secure-scraper-key-change-this"
SCRAPER_PATH = "../scraper"
