key_mapping:
  mapping_source: "key_libraby.py"

config:
  - zone: "China"
    type: "house"
    start_urls:
      - "https://sz.centanet.com/chengjiao/"
    fields:
      building_name_zh: building_name_zh
      house_type: house_type
      area: area
      town: town
      deal_price: deal_price
      deal_date: deal_date
      type_raw: type_raw
      floor: floor
      unit: unit
      city: city
      province: province
      street: street
      source_url: source_url
    xpaths:
      rows: ["//div[contains(@class,'estate-item')]", "//div[@class='estate-item clearfix']"]  # Target individual property items
      building_name_zh: [".//div[contains(@class,'item-info')]//h3//text()", ".//h3//text()", ".//div[contains(@class,'item-info')]//a//text()"]  # Property name like "星海名城（一期）"
      house_type: [".//div[contains(@class,'item-info')]//text()[contains(.,'室')]", ".//text()[contains(.,'室')]"]  # Room details like "2室2厅1卫"
      area: [".//div[contains(@class,'item-info')]//text()[contains(.,'平')]", ".//text()[contains(.,'平')]"]  # Area like "70.27平"
      town: [".//div[contains(@class,'item-info')]//text()[contains(.,'福田') or contains(.,'罗湖') or contains(.,'南山') or contains(.,'龙岗') or contains(.,'宝安') or contains(.,'龙华') or contains(.,'盐田') or contains(.,'光明') or contains(.,'坪山') or contains(.,'大鹏新区') or contains(.,'东莞')]", ".//text()[contains(.,'南山') or contains(.,'前海')]"]  # Location like "南山-前海"
      deal_price: [".//div[contains(@class,'item-pricearea')]//text()[contains(.,'万')]", ".//text()[contains(.,'万')]"]  # Price like "445万"
      deal_date: [".//span[@class='house-txt-time']/text()", ".//span[contains(@class,'house-txt-time')]//text()", ".//text()[contains(.,'2025/')]"]  # Date extraction
      type_raw: "住宅"  # Default type for houses
      floor: [".//text()[contains(.,'层')]"]  # Floor information if available
      unit: [".//text()[contains(.,'室')]"]  # Unit info from room details
      city: "深圳"
      province: "廣東"
      street: [".//a[contains(@href,'/chengjiao/') and not(contains(@href,'nanshan') or contains(@href,'futian') or contains(@href,'luohu') or contains(@href,'longgang') or contains(@href,'baoan') or contains(@href,'longhua') or contains(@href,'yantian') or contains(@href,'guangming') or contains(@href,'pingshan') or contains(@href,'dapeng'))]//text()", ".//a[contains(@href,'qianhai') or contains(@href,'houhai') or contains(@href,'chegongmiao')]//text()"]  # Street/area from location links, excluding district links
      source_url: [".//a[contains(@href,'/xiaoqu/')]/@href", ".//a[contains(@href,'/ershoufang/')]/@href", ".//a/@href"]  # Extract property detail page URL (xiaoqu pages are property details)