key_mapping:
  mapping_source: "key_library.py"

config:
  - zone: "Hong Kong"
    type: store
    start_urls:
      - "https://www.midlandici.com.hk/ics/property/transaction/sold?lang=zh-hk"
    fields:
      type: type
      building_name_zh: building_name_zh
      floor: floor
      unit: flat
      area: area
      deal_date: tx_date
      deal_price: sell
    xpaths:
      rows: ["//tbody/tr[position() >= 1]"]  # Start from tr[1] and continue for all rows
      type: ["./td[2]//text()"]
      building_name_zh: ["./td[3]/.//text()", "./td[3]/span[@class='building-name']//text()"]  # Extract from building-name span
      floor: ["./td[3]//text()"]  # Extract floor from building name text  
      unit: ["./td[3]//text()"]   # Extract unit from building name text
      tx_date: ["./td[1]/span[@class='transaction-date']/text()", "./td[1]//@*[contains(., '2025')]", "./td[1]//text()[normalize-space()]"]  # Multiple strategies for date extraction
      area: ["./td[4]/div/span[@class='area-value']//text()", "./td[4]//text()"]   # Extract from area-value span
      sell: ["./td[6]/div/span[@class='price-total-value']/text()", "./td[6]//text()[contains(., '$')]", "./td[6]//text()[normalize-space()]"]  # Multiple strategies for price extraction


  - zone: "Hong Kong"
    type: store
    start_urls:
      - "https://oir.centanet.com/transaction/sale/"
    fields:
      type: type
      building_name_zh: propertyNameCn
      floor: floor
      unit: unit
      area: area
      deal_date: deal_date
      deal_price: deal_price
    xpaths:
      rows: ["//tbody/tr[position() >= 1]"]  # Start from tr[1] and continue for all rows
      type: ["./td[2]//text()"]
      propertyNameCn: ["./td[4]//a//text()", "./td[4]//text()", "./td[3]//text()"]  # Building name in td[4] link, fallback to district in td[3]
      floor: ["./td[5]//text()"]
      unit: ["./td[6]//text()"]
      area: ["./td[7]//text()"]
      deal_date: ["./td[1]//text()"]
      deal_price: ["./td[8]//text()"]

  - zone: "Hong Kong"
    type: carpark
    start_urls:
      - "https://carparkhk.com/transaction-records.php?area=&years=&month=#gsc.tab=0"
    fields:
      type: type
      building_name_zh: propertyNameCn
      floor: floor_unit_combined  # Will be split in processing
      unit: floor_unit_combined   # Will be split in processing  
      area: area
      deal_date: deal_date
      deal_price: deal_price_millions  # Will be converted from millions
    xpaths:
      rows: ["//tr[position() > 1]"]  # Skip header row, no tbody
      type: ["./td[1]//text()"]  # We'll override this in spider logic
      propertyNameCn: ["./td[2]/a/text()", "./td[2]//text()[normalize-space()]", "./td[2]//text()"]  # Building name in td[2], inside link or all text with multiple fallbacks
      floor_unit_combined: ["./td[3]//text()"]  # Combined floor/unit like "2/P16"
      deal_price_millions: ["./td[4]//text()"]  # Price in millions like "0.970"
      deal_date: ["./td[5]//text()"]  # Date in td[5]
      area: ["./td[6]//text()"]  # Area might be in td[6] if exists