key_mapping:
  mapping_source: "key_library.py"

config:
  - zone: "Hong Kong"
    type: store
    start_urls:
      - "https://oir.centanet.com/transaction/search/?daterang=01%2F07%2F2025-01%2F08%2F2025&posttype=S"
    fields:
      type: type
      building_name_zh: building_name_zh
      district: district
      floor: floor
      unit: unit
      area: area
      deal_date: deal_date
      deal_price: deal_price
      price_per_sqft: price_per_sqft
    xpaths:
      type: ["./td[2]//text()"]
      building_name_zh: ["./td[4]//a//text()"]
      district: ["./td[3]//text()"]
      floor: ["./td[5]//text()"]
      unit: ["./td[6]//text()"]
      area: ["./td[7]//text()"]
      deal_date: ["./td[1]//text()"]
      deal_price: ["./td[8]//text()"]
      price_per_sqft: ["./td[9]//text()"]
