store_types:
  寫字樓: ['寫字樓']
  工商: ['工商']
  商舖: ['商舖']
  車位: ['車位']
  辦公室: ['辦公室']
  廠房: ['廠房']
  倉庫: ['倉庫']
  地段: ['地段']
  # Chinese property types (Lianjia)
  写字楼: ['写字楼']
  商铺: ['商铺']
  厂房: ['厂房']
  仓库: ['仓库']

house_types:
  住宅單位: ['住宅單位']
  別墅: ['別墅']
  公寓: ['公寓']
  住宅: ['住宅']
  # Chinese house types (Lianjia)
  住宅: ['住宅']
  别墅: ['别墅']
  公寓: ['公寓']
  复式: ['复式']
  平层: ['平层']