store_types:
  寫字樓: ['c']
  工商: ['i']
  商舖: ['s','shop']
  車位: ['parking']
  辦公室: ['office']
  廠房: ['factory']
  倉庫: ['warehouse']
  地段: ['land']

house_types:
  住宅單位: ['residential']
  別墅: ['villa']
  公寓: ['apartment']